### ISSUE TITLE
Missing .kitchen.yml file

### ISSUE THREAD

**Issue by asurak** [chef/dotscaleworkshop#1]
The file dotscaleworkshop/cdwithjenkins/.kitchen.yml seems to be missing

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: ["\xE2" on US-ASCII]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

E, [2015-06-05T19:07:14.637064 #32448] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
rake aborted!
Command failed with status (20): [kitchen converge...]
/Users/adams/GitRepos/dotScaleWorkshop/dotscaleworkshop/cdwithjenkins/Rakefile:3:in `block (2 levels) in <top (required)>'
/Users/adams/GitRepos/dotScaleWorkshop/dotscaleworkshop/cdwithjenkins/Rakefile:2:in `chdir'
/Users/adams/GitRepos/dotScaleWorkshop/dotscaleworkshop/cdwithjenkins/Rakefile:2:in `block in <top (required)>'
Tasks: TOP => converge
(See full trace by running task with --trace)
```

Output of kitchen diagnose --all:

```

---
timestamp: 2015-06-05 17:07:19 UTC
kitchen_version: 1.4.0
plugins:
  error:
    exception: "#<Kitchen::UserError: Kitchen YAML file /Users/adams/GitRepos/dotScaleWorkshop/dotscaleworkshop/cdwithjenkins/.kitchen.yml
      does not exist.>"
    message: Kitchen YAML file /Users/adams/GitRepos/dotScaleWorkshop/dotscaleworkshop/cdwithjenkins/.kitchen.yml
      does not exist.
    backtrace:
```

**Comment by thommay** [comment]
Hi,
the `.kitchen.yml` file is in the setup directory. If you run `rake converge`, it runs `kitchen converge` in the setup directory. 
Thanks for the report, and hope this clears things up.
-Thom

**Comment by asurak** [comment]
The converge action does not finish with success, even when manually run inside setup

```
I, [2015-06-05T22:48:53.716721 #33098]  INFO -- Kitchen: -----> Starting Kitchen (v1.4.0)
I, [2015-06-05T22:48:54.239743 #33098]  INFO -- Kitchen: -----> Converging <default-centos-66>...
E, [2015-06-05T22:48:56.599757 #33098] ERROR -- Kitchen: ------Exception-------
E, [2015-06-05T22:48:56.599864 #33098] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2015-06-05T22:48:56.599887 #33098] ERROR -- Kitchen: Message: Failed to complete #converge action: ["\xE2" on US-ASCII]
E, [2015-06-05T22:48:56.599902 #33098] ERROR -- Kitchen: ---Nested Exception---
E, [2015-06-05T22:48:56.599914 #33098] ERROR -- Kitchen: Class: Encoding::InvalidByteSequenceError
E, [2015-06-05T22:48:56.599925 #33098] ERROR -- Kitchen: Message: "\xE2" on US-ASCII
E, [2015-06-05T22:48:56.599936 #33098] ERROR -- Kitchen: ------Backtrace-------
E, [2015-06-05T22:48:56.599948 #33098] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `encode'
E, [2015-06-05T22:48:56.599959 #33098] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize'
E, [2015-06-05T22:48:56.599972 #33098] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `new'
E, [2015-06-05T22:48:56.599983 #33098] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
E, [2015-06-05T22:48:56.599995 #33098] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:473:in `from_json'
E, [2015-06-05T22:48:56.600006 #33098] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:29:in `from_json'
E, [2015-06-05T22:48:56.600017 #33098] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook.rb:36:in `from_path'
E, [2015-06-05T22:48:56.600029 #33098] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/cached_cookbook.rb:15:in `from_store_path'
```
